using QuikytLoader.Application.Interfaces.Services;
using QuikytLoader.Domain.Common;
using QuikytLoader.Domain.Entities;
using QuikytLoader.Infrastructure.Youtube.ACL.Services;

namespace QuikytLoader.Infrastructure.Youtube.Subtitles;

internal sealed class YoutubeSubtitlesService(IYtDlpAcl ytDlpAcl) : IYoutubeSubtitlesService
{
    private readonly Dictionary<Guid, CancellationTokenSource> _cancellationTokens = [];

    public async Task<Result<IReadOnlyDictionary<string, string>?>> FetchManualSubtitlesAsync(
        Guid itemId,
        DownloadSource downloadSource,
        string tempDirectory)
    {
        var cts = _cancellationTokens[itemId] = new CancellationTokenSource();
        var ct = cts.Token;

        try
        {
            var downloadSubtitlesResult = await ytDlpAcl.DownloadSubtitlesAsync(
                downloadSource.YoutubeVideoId,
                tempDirectory,
                _cancellationTokens[itemId].Token);

            if (!downloadSubtitlesResult.IsSuccess)
                return downloadSubtitlesResult.Error;

            var subtitlesFiles = Directory.GetFiles(tempDirectory, "*.srt");
            if (subtitlesFiles.Length != 0)
                return Result<IReadOnlyDictionary<string, string>?>.Success(
                    await GetSubtitlesFileContentsAsync(subtitlesFiles, ct));

            // -- No Subtitles Found
            return Result<IReadOnlyDictionary<string, string>?>.Success(null);
        }
        finally
        {
            cts.Dispose();
            _cancellationTokens.Remove(itemId);
        }
    }

    public async Task<Result<IReadOnlyDictionary<string, string>?>> FetchAutoSubtitlesAsync(
        Guid itemId,
        DownloadSource downloadSource,
        string tempDirectory,
        string iso6391Code)
    {
        var cts = _cancellationTokens[itemId] = new CancellationTokenSource();
        var ct = cts.Token;

        try
        {
            var downloadSubtitlesResult = await ytDlpAcl.DownloadAutoGeneratedSubtitlesAsync(
                downloadSource.YoutubeVideoId,
                tempDirectory,
                iso6391Code,
                ct);

            if (!downloadSubtitlesResult.IsSuccess)
                return downloadSubtitlesResult.Error;

            var subtitlesFiles = Directory.GetFiles(tempDirectory, "*.srt");
            if (subtitlesFiles.Length != 0)
                return Result<IReadOnlyDictionary<string, string>?>.Success(
                    await GetSubtitlesFileContentsAsync(subtitlesFiles, ct));

            // -- No Subtitles Found
            return Result<IReadOnlyDictionary<string, string>?>.Success(null);
        }
        finally
        {
            cts.Dispose();
            _cancellationTokens.Remove(itemId);
        }
    }

    public void CancelSubtitlesFetching(Guid itemId) => _cancellationTokens[itemId].Cancel();

    private async Task<IReadOnlyDictionary<string, string>> GetSubtitlesFileContentsAsync(
        string[] subtitlesFiles,
        CancellationToken ct)
    {
        var subtitles = new Dictionary<string, string>(
            StringComparer.OrdinalIgnoreCase);

        foreach (var file in subtitlesFiles)
        {
            await CleanupSubtitlesFileAsync(file, ct);

            var language = Path.GetFileNameWithoutExtension(file)
                .Split('.')
                .Last();

            // Call Trim() because new line is automatically added in the end of the file
            subtitles[language] = (await File.ReadAllTextAsync(file, ct)).Trim();
        }

        return subtitles;
    }

    private static readonly System.Text.RegularExpressions.Regex SubtitlesNumberRegex =
        new(@"^[0-9]+$", System.Text.RegularExpressions.RegexOptions.Compiled);

    private static readonly System.Text.RegularExpressions.Regex HtmlTagRegex =
        new("<[^>]*>", System.Text.RegularExpressions.RegexOptions.Compiled);

    private static async Task CleanupSubtitlesFileAsync(string file, CancellationToken ct)
    {
        var lines = (await File.ReadAllLinesAsync(file, ct))
            .Where(line =>
                !SubtitlesNumberRegex.IsMatch(line) &&
                !line.Contains("-->"))
            .Select(line =>
                HtmlTagRegex.Replace(line, ""))
            .Where(line =>
                !string.IsNullOrWhiteSpace(line));

        await File.WriteAllLinesAsync(file, lines, ct);
    }
}
