using QuikytLoader.Domain.Common;
using QuikytLoader.Domain.Entities;
using QuikytLoader.Infrastructure.Youtube.ACL.RawModels;

namespace QuikytLoader.Infrastructure.Youtube.ACL.Services;

internal interface IYtDlpAcl
{
    Task<Result<YtDlpVideoRaw>> GetVideoAsync(
        DownloadSource downloadSource);

    Task<Result<YtDlpPlaylistRaw>> GetPlaylistAsync(
        DownloadPlaylistSource downloadPlaylistSource,
        int maxItems);

    Task<Result> DownloadAudioAsync(
        DownloadSource downloadSource,
        string downloadDirectory,
        string? fileName,
        Action<string>? onOutputLine,
        CancellationToken ct);

    Task<Result> DownloadSubtitlesAsync(
        string videoId,
        string outputDirectory,
        CancellationToken ct);

    Task<Result> DownloadAutoGeneratedSubtitlesAsync(
        string videoId,
        string outputDirectory,
        string language,
        CancellationToken ct);
}
