using System.Text.Json;
using QuikytLoader.Domain.Common;
using QuikytLoader.Domain.Entities;
using QuikytLoader.Infrastructure.Persistence.Json;
using QuikytLoader.Infrastructure.Youtube.ACL.RawModels;
using QuikytLoader.Infrastructure.Youtube.YtDlp;

namespace QuikytLoader.Infrastructure.Youtube.ACL.Services;

internal sealed class YtDlpAcl(IYtDlpProcessClient ytDlpProcessClient) : IYtDlpAcl
{
    public async Task<Result<YtDlpVideoRaw>> GetVideoAsync(
        DownloadSource downloadSource,
        CancellationToken ct)
    {
        var args = new[]
        {
            "--quiet",
            "--skip-download",
            "--no-playlist",
            "--dump-single-json",
            "--", downloadSource.YoutubeVideoId
        };

        var outputResult = await ytDlpProcessClient.RunCaptureAsync(args, ct);
        if (!outputResult.IsSuccess)
            return outputResult.Error;

        var parsed = JsonSerializer.Deserialize(
            outputResult.Value,
            AppJsonSerializerContext.Default.YtDlpVideoJson)!;

        return Result<YtDlpVideoRaw>.Success(
            new YtDlpVideoRaw(
                parsed.Title,
                parsed.Channel,
                parsed.Description,
                parsed.Duration));
    }

    public async Task<Result<YtDlpPlaylistRaw>> GetPlaylistAsync(
        DownloadPlaylistSource downloadPlaylistSource,
        int maxItems,
        CancellationToken ct)
    {
        var args = new[]
        {
            "--quiet",
            "--flat-playlist",
            "--playlist-items", $"1:{maxItems}",
            "--dump-single-json",
            "--", downloadPlaylistSource.YoutubePlaylistUrl
        };

        var outputResult = await ytDlpProcessClient.RunCaptureAsync(args, ct);
        if (!outputResult.IsSuccess)
            return outputResult.Error;

        var parsed = JsonSerializer.Deserialize(
            outputResult.Value,
            AppJsonSerializerContext.Default.YtDlpPlaylistJson)!;

        return Result<YtDlpPlaylistRaw>.Success(
            new YtDlpPlaylistRaw(
                parsed.Title,
                parsed.Entries
                    .Select(e =>
                        new YtDlpPlaylistEntryRaw(
                            e.Id,
                            e.Url,
                            e.Title,
                            e.Channel,
                            e.Description,
                            e.Duration))
                    .ToList()));
    }

    public Task<Result> DownloadAudioAsync(
        DownloadSource downloadSource,
        string downloadDirectory,
        string? fileName,
        Action<string>? onOutputLine,
        CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(fileName))
            fileName = "%(title)s";

        var outputPath = Path.Combine(
            downloadDirectory,
            fileName);

        var args = new[]
        {
            "--extract-audio",
            "--audio-format", "mp3",
            "--audio-quality", "0",
            "--output", $"{outputPath}.%(ext)s",
            "--no-playlist",
            "--add-metadata",
            "--embed-thumbnail",
            "--write-thumbnail",
            "--convert-thumbnails", "jpg",

            "--parse-metadata", $"{fileName}:%(meta_title)s",
            "--parse-metadata", "%(uploader)s:%(meta_artist)s",
            "--parse-metadata", "%(uploader)s:%(meta_album_artist)s",
            "--parse-metadata", "%(channel)s:%(meta_album)s",
            "--parse-metadata", "%(upload_date>%Y)s:%(meta_date)s",
            "--parse-metadata", "%(creator)s:%(meta_composer)s",
            "--parse-metadata", "%(uploader)s:%(meta_performer)s",
            "--parse-metadata", "%(description)s:%(meta_comment)s",
            "--parse-metadata", "%(channel)s:%(meta_publisher)s",
            "--parse-metadata", "%(webpage_url)s:%(meta_purl)s",
            "--parse-metadata", "%(genre)s:%(meta_genre)s",

            "--progress",
            "--", downloadSource.YoutubeVideoId
        };

        return ytDlpProcessClient.RunStreamingAsync(
            args,
            onOutputLine,
            ct);
    }

    public Task<Result> DownloadSubtitlesAsync(
        string videoId,
        string outputDirectory,
        CancellationToken ct)
    {
        var args = BuildSubtitleArguments(
            videoId,
            outputDirectory,
            null);

        return ytDlpProcessClient.RunStreamingAsync(
            args,
            ct: ct);
    }

    public Task<Result> DownloadAutoGeneratedSubtitlesAsync(
        string videoId,
        string outputDirectory,
        string language,
        CancellationToken ct)
    {
        var args = BuildSubtitleArguments(
            videoId,
            outputDirectory,
            language);

        return ytDlpProcessClient.RunStreamingAsync(
            args,
            ct: ct);
    }

    private static List<string> BuildSubtitleArguments(
        string videoId,
        string outputDirectory,
        string? language)
    {
        var outputPath = Path.Combine(
            outputDirectory,
            videoId);

        var args = new List<string>
        {
            "--skip-download",
            "--sub-format", "ttml",
            "--convert-subs", "srt",
            "--output", outputPath,
            "--no-playlist"
        };

        if (language is not null)
        {
            args.Add("--write-auto-subs");
            args.Add("--sub-langs");
            args.Add(language);
        }
        else
        {
            args.Add("--write-subs");
            args.Add("--sub-langs");
            args.Add("all");
        }

        args.Add("--");
        args.Add(videoId);

        return args;
    }
}
