using QuikytLoader.Application.Interfaces.Queue;
using QuikytLoader.Application.Interfaces.Services;
using QuikytLoader.Application.Interfaces.Temp;
using QuikytLoader.Domain.Common;
using QuikytLoader.Domain.Entities;
using QuikytLoader.Infrastructure.LanguageIdentification;
using QuikytLoader.Infrastructure.Youtube.ACL.Services;

namespace QuikytLoader.Infrastructure.Youtube.Subtitles;

internal sealed class YoutubeSubtitlesService(
    IDownloadQueue queue,
    IYtDlpAcl ytDlpAcl,
    ITempDirectoryService tempDirectoryService,
    ILanguageIdentifier languageIdentifier,
    IYoutubeMetadataService youtubeMetadataService) : IYoutubeSubtitlesService
{
    private readonly Dictionary<Guid, CancellationTokenSource> _cancellationTokens = [];

    public async Task FetchSubtitlesAsync(Guid itemId)
    {
        var queueItem = queue.GetItem(itemId);
        // Subtitles have already been loaded or are currently loading or are not allowed to be loaded
        if (queueItem.Subtitles is not null ||
            queueItem.AreSubtitlesLoading ||
            !queueItem.AllowSubtitlesLoading) return;

        queueItem.AreSubtitlesLoading = true;
        queueItem.SubtitlesError = null;
        queue.UpdateItem(queueItem.Id);

        _cancellationTokens[queueItem.Id] = new CancellationTokenSource();

        try
        {
            var subtitlesResult = await GetSubtitlesAsync(queueItem.Source, queueItem, _cancellationTokens[queueItem.Id].Token);
            if (!subtitlesResult.IsSuccess)
            {
                queueItem.SubtitlesError = subtitlesResult.Error;
                return;
            }

            queueItem.Subtitles = subtitlesResult.Value;
            queueItem.AllowSubtitlesLoading = false;
            if (queueItem.Subtitles is null)
                queueItem.SubtitlesError = Errors.Youtube.SubtitlesNotFound();
        }
        catch (OperationCanceledException)
        {
            queueItem.SubtitlesError = Errors.Youtube.SubtitlesFetchCanceled();
        }
        finally
        {
            _cancellationTokens[queueItem.Id].Dispose();
            _cancellationTokens.Remove(queueItem.Id);
            queueItem.AreSubtitlesLoading = false;
            queue.UpdateItem(queueItem.Id);
        }
    }

    public void CancelSubtitles(Guid itemId) => _cancellationTokens[itemId].Cancel();

    private async Task<Result<IReadOnlyDictionary<string, string>?>> GetSubtitlesAsync(
        DownloadSource downloadSource,
        QueueItem queueItem,
        CancellationToken ct)
    {
        var subtitlesDirectory =
            tempDirectoryService.CreateSubdirectory(downloadSource.YoutubeVideoId, "subtitles");

        try
        {
            // -- Manual Subtitles Fetch
            var downloadSubtitlesResult = await ytDlpAcl.DownloadSubtitlesAsync(
                downloadSource.YoutubeVideoId,
                subtitlesDirectory,
                ct);
            if (!downloadSubtitlesResult.IsSuccess) return downloadSubtitlesResult.Error;
            var subtitleFiles = Directory.GetFiles(subtitlesDirectory, "*.srt");
            if (subtitleFiles.Length != 0)
                return Result<IReadOnlyDictionary<string, string>?>.Success(
                    await GetSubtitleFileContentsAsync(subtitleFiles, false, ct));

            // -- Auto Generated Subtitles Fetch
            var videoMetadata = queueItem.Metadata;
            if (videoMetadata is null)
            {
                var videoMetadataResult = await youtubeMetadataService.GetVideoMetadataAsync(queueItem.Source);
                if (!videoMetadataResult.IsSuccess) return videoMetadataResult.Error;
                videoMetadata = videoMetadataResult.Value;
            }

            downloadSubtitlesResult = await ytDlpAcl.DownloadAutoGeneratedSubtitlesAsync(
                downloadSource.YoutubeVideoId,
                subtitlesDirectory,
                languageIdentifier.Identify($"{videoMetadata.Title}\n{videoMetadata.Description}"),
                ct);
            if (!downloadSubtitlesResult.IsSuccess) return downloadSubtitlesResult.Error;
            subtitleFiles = Directory.GetFiles(subtitlesDirectory, "*.srt");
            if (subtitleFiles.Length != 0)
                return Result<IReadOnlyDictionary<string, string>?>.Success(
                    await GetSubtitleFileContentsAsync(subtitleFiles, true, ct));

            // -- No Subtitles Found
            return Result<IReadOnlyDictionary<string, string>?>.Success(null);
        }
        finally
        {
            tempDirectoryService.DeleteSubdirectory(subtitlesDirectory);
        }
    }

    private async Task<IReadOnlyDictionary<string, string>> GetSubtitleFileContentsAsync(
        string[] subtitleFiles,
        bool isAutoGenerated,
        CancellationToken ct)
    {
        var subtitles = new Dictionary<string, string>(
            StringComparer.OrdinalIgnoreCase);

        foreach (var file in subtitleFiles)
        {
            await CleanupSubtitleFileAsync(file, ct);

            var language = Path.GetFileNameWithoutExtension(file)
                .Split('.')
                .Last();

            if (isAutoGenerated)
                language += " (auto-generated)";

            subtitles[language] = await File.ReadAllTextAsync(file, ct);
        }

        return subtitles;
    }

    private static readonly System.Text.RegularExpressions.Regex SubtitleNumberRegex =
        new(@"^[0-9]+$", System.Text.RegularExpressions.RegexOptions.Compiled);

    private static readonly System.Text.RegularExpressions.Regex HtmlTagRegex =
        new("<[^>]*>", System.Text.RegularExpressions.RegexOptions.Compiled);

    private static async Task CleanupSubtitleFileAsync(string file, CancellationToken ct)
    {
        var lines = (await File.ReadAllLinesAsync(file, ct))
            .Where(line =>
                !SubtitleNumberRegex.IsMatch(line) &&
                !line.Contains("-->"))
            .Select(line =>
                HtmlTagRegex.Replace(line, ""))
            .Where(line =>
                !string.IsNullOrWhiteSpace(line));

        await File.WriteAllLinesAsync(file, lines, ct);
    }
}
