using QuikytLoader.Application.Interfaces.Queue;
using QuikytLoader.Application.Interfaces.Services;
using QuikytLoader.Application.Interfaces.Temp;
using QuikytLoader.Domain.Common;
using QuikytLoader.Domain.Entities;
using QuikytLoader.Infrastructure.Youtube.ACL.Services;

namespace QuikytLoader.Infrastructure.Services;

internal sealed class YoutubeSubtitlesService(IDownloadQueue queue, IYtDlpAcl ytDlpAcl, ITempDirectoryService tempDirectoryService) : IYoutubeSubtitlesService
{
    private readonly Dictionary<Guid, CancellationTokenSource> _cancellationTokens = [];

    public async Task FetchSubtitlesAsync(Guid itemId)
    {
        var queueItem = queue.GetItem(itemId);
        // Subtitles have already been loaded or are currently loading or are not allowed to be loaded
        if (queueItem.Subtitles is not null ||
            queueItem.AreSubtitlesLoading ||
            !queueItem.AllowSubtitlesLoading) return;

        queueItem.AreSubtitlesLoading = true;
        queueItem.SubtitlesError = null;
        queue.UpdateItem(queueItem.Id);

        _cancellationTokens[queueItem.Id] = new CancellationTokenSource();

        try
        {
            var subtitlesResult = await GetVideoSubtitlesAsync(queueItem.Source, _cancellationTokens[queueItem.Id].Token);
            if (!subtitlesResult.IsSuccess)
            {
                queueItem.SubtitlesError = subtitlesResult.Error;
            }
            else
            {
                queueItem.Subtitles = subtitlesResult.Value;
                queueItem.AllowSubtitlesLoading = false;
                if (queueItem.Subtitles is null)
                    queueItem.SubtitlesError = Errors.Youtube.SubtitlesNotFound();
            }
        }
        catch (OperationCanceledException)
        {
            queueItem.SubtitlesError = Errors.Youtube.SubtitlesFetchCanceled();
        }
        finally
        {
            _cancellationTokens[queueItem.Id].Dispose();
            _cancellationTokens.Remove(queueItem.Id);
            queueItem.AreSubtitlesLoading = false;
            queue.UpdateItem(queueItem.Id);
        }
    }

    public void CancelSubtitles(Guid itemId) => _cancellationTokens[itemId].Cancel();

    private async Task<Result<IReadOnlyDictionary<string, string>?>> GetVideoSubtitlesAsync(
        DownloadSource downloadSource,
        CancellationToken ct)
    {
        var subtitlesDirectory =
            tempDirectoryService.CreateSubdirectory(downloadSource.YoutubeVideoId, "subtitles");

        try
        {
            var result = await ytDlpAcl.DownloadSubtitlesAsync(
                downloadSource.YoutubeVideoId,
                subtitlesDirectory,
                ct);

            if (!result.IsSuccess)
                return Errors.Youtube.SubtitlesFetchFailed(result.Error);

            var subtitleFiles = Directory.GetFiles(
                subtitlesDirectory,
                "*.srt");

            var isAutoGenerated = subtitleFiles.Length == 0;
            if (isAutoGenerated)
            {
                result = await ytDlpAcl.DownloadAutoGeneratedSubtitlesAsync(
                    downloadSource.YoutubeVideoId,
                    subtitlesDirectory,
                    ct);

                if (!result.IsSuccess)
                    return Errors.Youtube.SubtitlesFetchFailed(result.Error);

                subtitleFiles = Directory.GetFiles(
                    subtitlesDirectory,
                    "*.srt");
            }

            var subtitles = new Dictionary<string, string>(
                StringComparer.OrdinalIgnoreCase);

            foreach (var file in subtitleFiles)
            {
                await CleanupSubtitleFileAsync(file, ct);

                var language = Path.GetFileNameWithoutExtension(file)
                    .Split('.')
                    .Last();

                if (isAutoGenerated)
                    language += " (auto-generated)";

                subtitles[language] = await File.ReadAllTextAsync(
                    file,
                    ct);
            }

            return subtitles.Count == 0 ? null : subtitles;
        }
        finally
        {
            tempDirectoryService.DeleteSubdirectory(subtitlesDirectory);
        }
    }

    private static readonly System.Text.RegularExpressions.Regex SubtitleNumberRegex =
        new(@"^[0-9]+$", System.Text.RegularExpressions.RegexOptions.Compiled);

    private static readonly System.Text.RegularExpressions.Regex HtmlTagRegex =
        new("<[^>]*>", System.Text.RegularExpressions.RegexOptions.Compiled);

    private static async Task CleanupSubtitleFileAsync(string file, CancellationToken ct)
    {
        var lines = (await File.ReadAllLinesAsync(file, ct))
            .Where(line =>
                !SubtitleNumberRegex.IsMatch(line) &&
                !line.Contains("-->"))
            .Select(line =>
                HtmlTagRegex.Replace(line, ""))
            .Where(line =>
                !string.IsNullOrWhiteSpace(line));

        await File.WriteAllLinesAsync(file, lines, ct);
    }
}
