using QuikytLoader.Application.Interfaces.Queue;
using QuikytLoader.Application.Interfaces.Services;
using QuikytLoader.Application.Interfaces.Temp;
using QuikytLoader.Domain.Common;
using QuikytLoader.Domain.Entities;
using QuikytLoader.Infrastructure.Youtube.ACL.Services;

namespace QuikytLoader.Infrastructure.Services;

internal sealed class YoutubeSubtitlesService(IDownloadQueue queue, IYtDlpAcl ytDlpAcl, ITempDirectoryService tempDirectoryService) : IYoutubeSubtitlesService
{
    private readonly Dictionary<Guid, CancellationTokenSource> _cancellationTokens = [];

    public async Task FetchSubtitlesAsync(Guid itemId)
    {
        var queueItem = queue.GetItem(itemId);
        // Subtitles have already been loaded or are currently loading
        if (queueItem.Subtitles is not null || queueItem.AreSubtitlesLoading) return;

        queueItem.AreSubtitlesLoading = true;
        queueItem.SubtitlesError = null;
        queue.UpdateItem(queueItem.Id);

        using var cancellationTokenSource = _cancellationTokens[queueItem.Id] = new CancellationTokenSource();

        try
        {
            var subtitlesResult = await GetVideoSubtitlesAsync(queueItem.Source, cancellationTokenSource.Token);
            if (!subtitlesResult.IsSuccess)
            {
                queueItem.SubtitlesError = subtitlesResult.Error;
            }
            else
            {
                queueItem.Subtitles = subtitlesResult.Value;
                if (subtitlesResult.Value.Count == 0)
                    queueItem.SubtitlesError = Errors.Youtube.SubtitlesNotFound();
            }
        }
        catch (OperationCanceledException)
        {
            queueItem.SubtitlesError = new Error("Subtitles fetch canceled");
        }

        queueItem.AreSubtitlesLoading = false;
        queue.UpdateItem(queueItem.Id);
    }

    public void CancelSubtitles(Guid itemId) => _cancellationTokens[itemId].Cancel();

    private async Task<Result<IReadOnlyDictionary<string, string>>> GetVideoSubtitlesAsync(
        DownloadSource downloadSource,
        CancellationToken ct)
    {
        var subtitleDirectory =
            tempDirectoryService.CreateSubdirectory(downloadSource.YoutubeVideoId);

        try
        {
            var result = await ytDlpAcl.DownloadSubtitlesAsync(
                downloadSource.YoutubeVideoId,
                subtitleDirectory,
                ct);

            if (!result.IsSuccess)
                return Errors.Youtube.SubtitlesFetchFailed(result.Error);

            var subtitleFiles = Directory.GetFiles(
                subtitleDirectory,
                "*.srt");

            var isAutoGenerated = subtitleFiles.Length == 0;
            if (isAutoGenerated)
            {
                result = await ytDlpAcl.DownloadAutoGeneratedSubtitlesAsync(
                    downloadSource.YoutubeVideoId,
                    subtitleDirectory,
                    ct);

                if (!result.IsSuccess)
                    return Errors.Youtube.SubtitlesFetchFailed(result.Error);

                subtitleFiles = Directory.GetFiles(
                    subtitleDirectory,
                    "*.srt");
            }

            var subtitles = new Dictionary<string, string>(
                StringComparer.OrdinalIgnoreCase);

            foreach (var file in subtitleFiles)
            {
                CleanupSubtitleFile(file);

                var language = Path.GetFileNameWithoutExtension(file)
                    .Split('.')
                    .Last();

                if (isAutoGenerated)
                    language += " (auto-generated)";

                subtitles[language] = await File.ReadAllTextAsync(
                    file,
                    ct);
            }

            return subtitles;
        }
        finally
        {
            tempDirectoryService.DeleteSubdirectory(downloadSource.YoutubeVideoId);
        }
    }

    private static void CleanupSubtitleFile(string file)
    {
        var lines = File.ReadAllLines(file)
            .Where(line =>
                !System.Text.RegularExpressions.Regex.IsMatch(line, @"^[0-9]+$") &&
                !line.Contains("-->"))
            .Select(line =>
                System.Text.RegularExpressions.Regex.Replace(line, "<[^>]*>", ""))
            .Where(line =>
                !string.IsNullOrWhiteSpace(line));

        File.WriteAllLines(file, lines);
    }
}
